version: '2.2'
services:
  chatfiles:
    image: guangzhengli/chatfiles:latest
    container_name: chatfiles
    ports:
      - 3000:3000
    environment:
      - OPENAI_TYPE=${OPENAI_TYPE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_DEPLOYMENT_NAME=${AZURE_OPENAI_API_DEPLOYMENT_NAME}
      - AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME=${AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME}
      - AZURE_OPENAI_API_INSTANCE_NAME=${AZURE_OPENAI_API_INSTANCE_NAME}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_CHAT_FILES_UPLOAD_PATH=public/uploads
      - NEXT_PUBLIC_CHAT_FILES_MAX_SIZE=0