version: '3'

services:
  chat-email:
    image: kongpf8848/chat-email:latest
    container_name: chat-email
    ports:
      - 3000:3000
    environment:
      - OPENAI_TYPE=${OPENAI_TYPE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_DEPLOYMENT_NAME=${AZURE_OPENAI_API_DEPLOYMENT_NAME}
      - AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME=${AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME}
      - AZURE_OPENAI_API_INSTANCE_NAME=${AZURE_OPENAI_API_INSTANCE_NAME}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - SUPABASE_API_URL=${SUPABASE_API_URL}
      - NEXT_PUBLIC_CHAT_FILES_UPLOAD_PATH=public/uploads
      - NEXT_PUBLIC_CHAT_FILES_MAX_SIZE=10000000